# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TruenasScaleAcme < Formula
  desc "Optain and manage certificates for TrueNAS Scale."
  homepage "https://github.com/thde/truenas-scale-acme"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.5.0/truenas-scale-acme_0.5.0_darwin_arm64.tar.gz"
      sha256 "98e78e841467c13568103b97b01cdb5875ab1c0be5e97d12a1c3b237098be087"

      def install
        bin.install "truenas-scale-acme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.5.0/truenas-scale-acme_0.5.0_darwin_amd64.tar.gz"
      sha256 "51715279aed64d7d854e5e0fcdbda088c9c4a972cb8c373589711fc37a936589"

      def install
        bin.install "truenas-scale-acme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.5.0/truenas-scale-acme_0.5.0_linux_arm64.tar.gz"
      sha256 "22c4fe1ab12013b6e684a57629a0cdc5860a888438fce919c91149b755ac2f3c"

      def install
        bin.install "truenas-scale-acme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.5.0/truenas-scale-acme_0.5.0_linux_amd64.tar.gz"
      sha256 "d5b75f23a49af03b005497d0db14c91b6b0beb513f2f52f16f1024e4b0ee3999"

      def install
        bin.install "truenas-scale-acme"
      end
    end
  end
end
