# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TruenasScaleAcme < Formula
  desc "Optain and manage certificates for TrueNAS Scale."
  homepage "https://github.com/thde/truenas-scale-acme"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.6.2/truenas-scale-acme_0.6.2_darwin_amd64.tar.gz"
      sha256 "e7be4d54d72f405ebd56123a795a74b6980ce8b413b8636fbe05e13e0ec3eb6a"

      def install
        bin.install "truenas-scale-acme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.6.2/truenas-scale-acme_0.6.2_darwin_arm64.tar.gz"
      sha256 "3f195a03a8f9578d832655999220c5469a16d9f34b5ea3adf4ce7ecec96d5bc4"

      def install
        bin.install "truenas-scale-acme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thde/truenas-scale-acme/releases/download/v0.6.2/truenas-scale-acme_0.6.2_linux_amd64.tar.gz"
        sha256 "d638e78cd2486f077d967bc109a9b8b5208f4d129b78bcd04b66144f0a780c49"

        def install
          bin.install "truenas-scale-acme"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thde/truenas-scale-acme/releases/download/v0.6.2/truenas-scale-acme_0.6.2_linux_arm64.tar.gz"
        sha256 "c32bde327af67f05fd0ebd9503e241fa29ee38263f8659335a4db27cef3e607c"

        def install
          bin.install "truenas-scale-acme"
        end
      end
    end
  end
end
