# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TruenasScaleAcme < Formula
  desc "Optain and manage certificates for TrueNAS Scale."
  homepage "https://github.com/thde/truenas-scale-acme"
  version "0.6.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.6.6/truenas-scale-acme_0.6.6_darwin_amd64.tar.gz"
      sha256 "9f0f18e3b78298d941c25ad9856af20da9249036f2f54b7cf07debd0d08dd2c0"

      def install
        bin.install "truenas-scale-acme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.6.6/truenas-scale-acme_0.6.6_darwin_arm64.tar.gz"
      sha256 "7a597cca3e937fb0a270c73154b31e52f4e58c93c180362d1ad463dc751e7b28"

      def install
        bin.install "truenas-scale-acme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.6.6/truenas-scale-acme_0.6.6_linux_amd64.tar.gz"
      sha256 "472135276ee06f22c1af331755cd6c5498962b259a8ebea20c9b663722808a27"
      def install
        bin.install "truenas-scale-acme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thde/truenas-scale-acme/releases/download/v0.6.6/truenas-scale-acme_0.6.6_linux_arm64.tar.gz"
      sha256 "d81bc28672d2a6d2876e1ccf3e91fe51b2ac9c9402d1c0177466233cf0b66798"
      def install
        bin.install "truenas-scale-acme"
      end
    end
  end
end
